// places_client/src/lib/components/Menu.svelte
<script lang="ts">
    import MenuButton from "$lib/components/MenuButton.svelte";
    import { routes } from "$lib/configs";
    import IconBookmark from "$lib/icons/IconBookmark.svelte";
    import IconDiscover from "$lib/icons/IconDiscover.svelte";
    import IconProfile from "$lib/icons/IconProfile.svelte";
</script>

<nav class="menu">
    <MenuButton icon={IconDiscover} route={routes.DISCOVER} text="Обзор" />
    <MenuButton icon={IconBookmark} route={routes.SAVED} text="Сохраненные" />
    <MenuButton icon={IconProfile} route={routes.PROFILE} text="Профиль" />
</nav>

<style>
    .menu {
        display: flex;
        justify-content: center;
        padding: var(--size-16);
        border-radius: 32px 32px 0 0;
        background-color: var(--color-white);
        gap: var(--size-24);
    }
</style>

// client/components/Menu.tsx
import { useLocation, useNavigate } from 'react-router-dom';
import MenuButton from 'components/MenuButton.tsx';
import IconDiscover from 'icons/IconDiscover.tsx';
import IconProfile from 'icons/IconProfile.tsx';
import { useEffect, useState } from 'react';

type PropsTypes = {

};

function Menu({}: PropsTypes) {
    const location = useLocation();
    const navigate = useNavigate();
    const [currentRoute, setCurrentRoute] = useState(location.pathname);

    useEffect(() => {
        setCurrentRoute(location.pathname);
    }, [location.pathname]);

    function onClick(route: string) {
        if (currentRoute !== route) {
            navigate(route);
        }
    }

    return (
        <footer className="flex p-m rounded-t-global bg-white">
            <MenuButton
                icon={<IconDiscover />}
                text="Просмотр"
                active={currentRoute === '/discover'}
                onClick={() => onClick('/discover')}
            />
            <MenuButton
                icon={<IconProfile />}
                text="Профиль"
                active={currentRoute === '/profile'}
                onClick={() => onClick('/profile')}
            />
        </footer>
    );
}

export default Menu;
