// client/components/MenuButton.tsx
import { ReactNode } from 'react';

interface MenuButtonProps {
    icon: ReactNode;
    text: string;
    active: boolean;
    onClick: () => void;
}

function MenuButton({ icon, text, active, onClick } : MenuButtonProps) {
    let color = active ? 'text-white' : 'text-black';
    let bgColor = active ? 'bg-black' : 'bg-white';

    return (
        <button onClick={onClick} className={`flex h-[48px] w-full rounded-block gap-s flex-row justify-center items-center ${color} ${bgColor}`}>
            {icon}
            {active && text}
        </button>
    );
}

export default MenuButton;

// client/src/components/MenuButton.svelte
<script lang="ts">
    import type { ComponentType } from 'svelte';
    import { goto } from '$app/navigation';
    import { page } from '$app/stores';

    export let icon: ComponentType;
    export let text: string;
    export let route: string;

    function handleClick() {
        if (!active) {
            goto(route);
        }
    }

    $: active = $page.url.pathname === route;
</script>

<button
        on:click={handleClick}
        class={`flex h-[48px] w-full text-p rounded-block gap-s flex-row justify-center items-center ${active ? 'text-white' : 'text-black'} ${active ? 'bg-black' : 'bg-white'}`}
>
    <svelte:component this={icon} />
    {#if (active)}{text}{/if}
</button>
